language: python
sudo: false
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
matrix:
  include:
    - os: linux
      python: "2.6"
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "pypy"
    - os: osx
      language: generic
before_install:
  - scripts/mac-os-x-on-travis.sh
install:
  - pip install --requirement=requirements-flake8.txt
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - make check
  - coverage run setup.py test
after_success:
  coveralls
